# Deployment, Service, PVC
apps:
  # Main
  - name: main
    namespace: BNS
    image:
      repository: "ENTER_IMAGE_REPO/main" # ENTER_IMAGE_REPO
      tag: latest
    replicaCount: 3
    containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    persistence:
      enabled: true
      mountPath: /mnt/data
      accessMode: ReadWriteMany
      size: 1Gi
      storageClass: BNS-storage
  
  # Blog
  - name: blog
    namespace: BNS
    image:
      repository: "ENTER_IMAGE_REPO/blog" # ENTER_IMAGE_REPO
      tag: latest
    replicaCount: 3
    containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    persistence:
      enabled: true
      mountPath: /mnt/data
      accessMode: ReadWriteMany
      size: 1Gi
      storageClass: BNS-storage

  # News
  - name: news
    namespace: BNS
    image:
      repository: "ENTER_IMAGE_REPO/news" # ENTER_IMAGE_REPO
      tag: latest
    replicaCount: 3
    containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    persistence:
      enabled: true
      mountPath: /mnt/data
      accessMode: ReadWriteMany
      size: 1Gi
      storageClass: BNS-storage

  # Shop
  - name: shop
    namespace: BNS
    image:
      repository: "ENTER_IMAGE_REPO/shop" # ENTER_IMAGE_REPO
      tag: latest
    replicaCount: 3
    containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    persistence:
      enabled: true
      mountPath: /mnt/data
      accessMode: ReadWriteMany
      size: 1Gi
      storageClass: BNS-storage

# NFS-CSI
storageClass:
  name: BNS-storage
  server: "ENTER_NFS_IP" # ENTER_NFS_IP
  share: /shared
  reclaimPolicy: Delete
  mountOptions:
    - nfsvers=4.2

# KEDA
scaledObjects:
  # Main
  - name: main-scaler
    targetDeployment: main-deploy
    namespace: BNS
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
    cpu:
      type: Utilization
      value: "60"
    cron:
      timezone: Asia/Seoul
      start: "0 9 * * *"
      end: "0 18 * * *"
      desiredReplicas: "3"

  # Blog
  - name: blog-scaler
    targetDeployment: blog-deploy
    namespace: BNS
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
    cpu:
      type: Utilization
      value: "60"
    cron:
      timezone: Asia/Seoul
      start: "0 9 * * *"
      end: "0 18 * * *"
      desiredReplicas: "3"

  # News
  - name: news-scaler
    targetDeployment: news-deploy
    namespace: BNS
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
    cpu:
      type: Utilization
      value: "60"
    cron:
      timezone: Asia/Seoul
      start: "0 9 * * *"
      end: "0 18 * * *"
      desiredReplicas: "3"

  # Shop
  - name: shop-scaler
    targetDeployment: shop-deploy
    namespace: BNS
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
    cpu:
      type: Utilization
      value: "60"
    cron:
      timezone: Asia/Seoul
      start: "0 9 * * *"
      end: "0 18 * * *"
      desiredReplicas: "3"

# Metal LB
metallb:
  ipRange: "ENTER_IP_RANGE" # ENTER AVAILABLE IP RANGE
  poolName: metalLBpool
  namespace: metallb-system

# ingress-rules
ingress:
  className: nginx
  host: www."ENTER_URL".com # ENTER URL
  paths:
    - path: /
      serviceName: main-service
      servicePort: 80
    - path: /shop(/|$)
      serviceName: shop-service
      servicePort: 80
    - path: /blog(/|$)
      serviceName: blog-service
      servicePort: 80
    - path: /news(/|$)
      serviceName: news-service
      servicePort: 80

# Webhook
webhook:
  namespace: default
  image: jongseo22/webhook-server:latest