# KEDA-install-job
apiVersion: batch/v1
kind: Job
metadata:
  name: install-keda
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
        - name: keda-installer
          image: bitnami/helm
          command: ["/bin/sh", "-c"]
          args:
            - |
              helm repo add kedacore https://kedacore.github.io/charts && \
              helm repo update && \
              helm install keda kedacore/keda --namespace keda --create-namespace
      restartPolicy: Never
---
# KEDA Scaled Objects
{{- range .Values.scaledObjects }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  scaleTargetRef:
    name: {{ .targetDeployment }}
  pollingInterval: {{ .pollingInterval }}
  cooldownPeriod: {{ .cooldownPeriod }}
  minReplicaCount: {{ .minReplicaCount }}
  maxReplicaCount: {{ .maxReplicaCount }}
  triggers:
    - type: cpu
      metadata:
        type: {{ .cpu.type }}
        value: "{{ .cpu.value }}"
    - type: cron
      metadata:
        timezone: {{ .cron.timezone }}
        start: "{{ .cron.start }}"
        end: "{{ .cron.end }}"
        desiredReplicas: "{{ .cron.desiredReplicas }}"
---
{{- end }}