apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.metallb.poolName }}
  namespace: {{ .Values.metallb.namespace }}
spec:
  addresses:
    - {{ .Values.metallb.ipRange }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-l2
  namespace: {{ .Values.metallb.namespace }}
spec:
  ipAddressPools:
    - {{ .Values.metallb.poolName }}