apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: nfs.csi.k8s.io
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
mountOptions:
  {{- range .Values.storageClass.mountOptions }}
  - {{ . }}
  {{- end }}
parameters:
  server: {{ .Values.storageClass.server }}
  share: {{ .Values.storageClass.share }}